# Generated by Django 5.1.15 on 2026-05-06 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0005_add_visit_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_facility', models.CharField(help_text='Name or identifier of receiving facility', max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted at facility'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('outcome', models.TextField(blank=True)),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='children.child')),
                ('referring_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-referred_at'],
            },
        ),
    ]
