# Generated by Django 5.1.15 on 2026-05-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Additional clinical context for the receiving facility'),
        ),
        migrations.AddField(
            model_name='referral',
            name='urgency',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('SOON', 'Soon (within a week)'), ('URGENT', 'Urgent (within 24 h)')], default='ROUTINE', max_length=10),
        ),
    ]
