# Generated by Django 5.2.16 on 2026-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_add_urgency_clinical_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted at facility'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
