# Generated by Django 5.1.15 on 2026-04-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification'},
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('PUSH', 'Push Notification')], default='PUSH', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SAM_ALERT', 'SAM Alert — Severe malnutrition detected'), ('HIGH_RISK_ALERT', 'High risk assessment alert'), ('VACCINATION_REMINDER', 'Upcoming vaccination reminder'), ('VACCINATION_OVERDUE', 'Vaccination overdue'), ('GROWTH_RISK', 'Growth trajectory risk detected'), ('MISSED_VISIT', 'Child has not been seen recently'), ('ZONE_SUMMARY', 'Daily zone KPI summary'), ('CHW_INACTIVE', 'CHW has been inactive')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
