# Generated by Django 5.1.15 on 2026-05-06 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_notification_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SAM_ALERT', 'SAM Alert — Severe malnutrition detected'), ('HIGH_RISK_ALERT', 'High risk assessment alert'), ('VACCINATION_REMINDER', 'Upcoming vaccination reminder'), ('VACCINATION_OVERDUE', 'Vaccination overdue'), ('GROWTH_RISK', 'Growth trajectory risk detected'), ('MISSED_VISIT', 'Child has not been seen recently'), ('ZONE_SUMMARY', 'Daily zone KPI summary'), ('CHW_INACTIVE', 'CHW has been inactive'), ('VISIT_REQUEST_CREATED', 'New visit request from parent'), ('VISIT_REQUEST_ACCEPTED', 'Visit request accepted by CHW'), ('VISIT_REQUEST_DECLINED', 'Visit request declined'), ('VISIT_REQUEST_COMPLETED', 'Visit completed')], max_length=30),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scope_type', models.CharField(choices=[('CAMP', 'Entire Camp'), ('ZONE', 'Specific Zone'), ('ROLE', 'All users of a role'), ('GLOBAL', 'All users (Admin only)')], max_length=10)),
                ('scope_id', models.CharField(blank=True, help_text='Camp/Zone UUID or role string', max_length=100)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('PUSH', 'Push Notification')], default='PUSH', max_length=10)),
                ('body', models.TextField()),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.broadcast')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('broadcast', 'recipient')},
            },
        ),
    ]
