# Generated by Django 5.2.16 on 2026-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SAM_ALERT', 'SAM Alert — Severe malnutrition detected'), ('HIGH_RISK_ALERT', 'High risk assessment alert'), ('VACCINATION_REMINDER', 'Upcoming vaccination reminder'), ('VACCINATION_OVERDUE', 'Vaccination overdue'), ('GROWTH_RISK', 'Growth trajectory risk detected'), ('MISSED_VISIT', 'Child has not been seen recently'), ('ZONE_SUMMARY', 'Daily zone KPI summary'), ('CHW_INACTIVE', 'CHW has been inactive'), ('BROADCAST', 'Broadcast message'), ('VACCINATION_DONE', 'Vaccination successfully administered'), ('VISIT_REQUEST_CREATED', 'New visit request from parent'), ('VISIT_REQUEST_ACCEPTED', 'Visit request accepted by CHW'), ('VISIT_REQUEST_DECLINED', 'Visit request declined'), ('VISIT_REQUEST_COMPLETED', 'Visit completed')], db_index=True, max_length=30),
        ),
    ]
