# Generated by Django 5.2.13 on 2026-04-28 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('measurement_date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=1, help_text='Height/length in centimetres', max_digits=5)),
                ('muac_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Mid-Upper Arm Circumference in cm', max_digits=4, null=True)),
                ('oedema', models.BooleanField(default=False, help_text='Bilateral nutritional oedema present?')),
                ('weight_for_height_z', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_for_age_z', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_for_age_z', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nutrition_status', models.CharField(blank=True, choices=[('SAM', 'Severe Acute Malnutrition'), ('MAM', 'Moderate Acute Malnutrition'), ('NORMAL', 'Normal'), ('OVERWEIGHT', 'Overweight')], max_length=20)),
                ('ml_predicted_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ml_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('ml_risk_flags', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='children.child')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Record',
                'ordering': ['-measurement_date', '-created_at'],
            },
        ),
    ]
