# Generated by Django 5.1.15 on 2026-04-29 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0002_camp_code_camp_estimated_population_and_more'),
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='bmi_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('iot', 'IoT/BLE Device')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='head_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Beats per minute', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='model_version',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='respiratory_rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Breaths per minute', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='risk_factors',
            field=models.JSONField(blank=True, default=list, help_text='Top 5 SHAP factors from ML prediction'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='spo2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Blood oxygen saturation %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='symptom_flags',
            field=models.JSONField(blank=True, default=list, help_text='List of active symptoms: fever, cough, diarrhea, vomiting, rash, difficulty_breathing, lethargy, poor_feeding'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in °C', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records', to='camps.campzone'),
        ),
    ]
