# Generated by Django 5.1.15 on 2026-05-06 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('health_records', '0003_clinicalnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmendmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('reason', models.TextField()),
                ('before_data', models.JSONField(help_text='Snapshot of fields before amendment')),
                ('after_data', models.JSONField(help_text='Snapshot of fields after amendment')),
                ('amended_at', models.DateTimeField(auto_now_add=True)),
                ('amended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Amendment Log',
                'ordering': ['-amended_at'],
            },
        ),
    ]
