# Generated by Django 5.2.16 on 2026-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0004_phase7_closure_consent_amendment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='measurement_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, max_length=10, null=True),
        ),
    ]
