# Generated by Django 5.1.15 on 2026-05-11 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faqitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='answer_fr',
            field=models.TextField(blank=True, help_text='French'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_rw',
            field=models.TextField(blank=True, help_text='Kinyarwanda'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_fr',
            field=models.CharField(blank=True, help_text='French', max_length=500),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_rw',
            field=models.CharField(blank=True, help_text='Kinyarwanda', max_length=500),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(help_text='English'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=models.CharField(help_text='English', max_length=500),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, help_text='Denormalised for fast display', max_length=254)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=10)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_body', models.JSONField(blank=True, help_text='Sanitised request body (passwords/tokens stripped)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'), models.Index(fields=['path', 'timestamp'], name='core_auditl_path_b3cf78_idx')],
            },
        ),
    ]
