# Generated by Django 5.2.16 on 2026-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], db_index=True, default='OPEN', max_length=10),
        ),
    ]
