# Generated by Django 5.1.15 on 2026-04-29 19:06

from django.db import migrations, models


def nullify_empty_phone_numbers(apps, schema_editor):
    """Convert empty string phone numbers to NULL before adding unique constraint."""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    # Use raw SQL to avoid model-level constraints during migration
    schema_editor.connection.cursor().execute(
        "UPDATE accounts_customuser SET phone_number = NULL WHERE phone_number = ''"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_parent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Must be approved by a manager before logging in'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('rw', 'Kinyarwanda'), ('fr', 'French'), ('en', 'English')], default='rw', max_length=5),
        ),
        # Step 1: Make phone_number nullable (no unique yet) — allows NULL values
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        # Step 2: Convert empty strings to NULL
        migrations.RunPython(nullify_empty_phone_numbers, migrations.RunPython.noop),
        # Step 3: Now safe to add the unique index
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
