# Generated by Django 5.1.15 on 2026-05-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_phase7_closure_consent_amendment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
