# Generated by Django 5.1.15 on 2026-04-29 19:06

import django.db.models.deletion
from django.db import migrations, models


def assign_unique_qr_codes(apps, schema_editor):
    """Assign a unique qr_code to every child that has an empty-string code."""
    import uuid
    Child = apps.get_model('children', 'Child')
    for child in Child.objects.filter(qr_code=''):
        Child.objects.filter(pk=child.pk).update(qr_code=uuid.uuid4().hex)


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0002_camp_code_camp_estimated_population_and_more'),
        ('children', '0002_guardian_user_link'),
    ]

    operations = [
        # Step 1: Add qr_code with empty-string default, no unique yet
        migrations.AddField(
            model_name='child',
            name='qr_code',
            field=models.CharField(blank=True, max_length=64, default=''),
        ),
        # Step 2: Assign a unique hex UUID to every existing row
        migrations.RunPython(assign_unique_qr_codes, migrations.RunPython.noop),
        # Step 3: Now safe to add the unique + db_index
        migrations.AlterField(
            model_name='child',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='child',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='camps.campzone'),
        ),
    ]
