# Generated by Django 5.1.15 on 2026-05-05 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_qr_code_child_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='assigned_chw',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CHW'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guardians', to=settings.AUTH_USER_MODEL),
        ),
    ]
