# Generated by Django 5.1.15 on 2026-05-05 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_add_assigned_chw_to_guardian'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('SOON', 'Soon (within a week)'), ('URGENT', 'Urgent (within 24 h)')], default='ROUTINE', max_length=10)),
                ('concern_text', models.TextField(blank=True)),
                ('symptom_flags', models.JSONField(blank=True, default=list, help_text='List of symptom strings e.g. ["fever","diarrhea"]')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('eta', models.DateTimeField(blank=True, help_text='Estimated time of arrival provided by the CHW', null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_chw', models.ForeignKey(blank=True, limit_choices_to={'role': 'CHW'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_visit_requests', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='children.child')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_visit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit Request',
                'ordering': ['-created_at'],
            },
        ),
    ]
