# Generated by Django 5.1.15 on 2026-05-06 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0002_camp_code_camp_estimated_population_and_more'),
        ('children', '0005_add_visit_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='closure_status',
            field=models.CharField(db_index=True, default='ACTIVE', help_text='ACTIVE (default), TRANSFERRED, DECEASED, or DEPARTED', max_length=15),
        ),
        migrations.CreateModel(
            name='ChildClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred'), ('DECEASED', 'Deceased'), ('DEPARTED', 'Departed from camp')], max_length=15)),
                ('reason', models.TextField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='children.child')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child Closure',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildZoneTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_transfers', to='children.child')),
                ('from_camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_transfers', to='camps.camp')),
                ('from_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_transfers', to='camps.campzone')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_transfers', to='camps.camp')),
                ('to_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_transfers', to='camps.campzone')),
            ],
            options={
                'verbose_name': 'Zone Transfer',
                'ordering': ['-created_at'],
            },
        ),
    ]
