# Generated by Django 5.1.15 on 2026-05-06 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_phase7_closure_consent_amendment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='Set when a nurse requests deletion; permanent purge runs 3 days later.', null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='deletion_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
