# Generated by Django 5.1.15 on 2026-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0007_add_deletion_fields_to_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=10),
        ),
    ]
