# Generated by Django 5.1.15 on 2026-05-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0008_add_withdrawn_visit_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Stored in E.164 format (+250XXXXXXXXX) after normalization.', max_length=20),
        ),
    ]
