# Generated by Django 5.1.15 on 2026-05-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0009_normalize_guardian_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='birth_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Birth weight in kilograms (e.g. 3.25)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='feeding_type',
            field=models.CharField(blank=True, choices=[('BREAST', 'Exclusive Breastfeeding'), ('FORMULA', 'Formula'), ('MIXED', 'Mixed')], help_text='Infant feeding method at time of registration', max_length=10),
        ),
        migrations.AddField(
            model_name='child',
            name='gestational_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Gestational age in weeks at birth (e.g. 38)', null=True),
        ),
    ]
