# Generated by Django 5.1.15 on 2026-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0010_child_neonatal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='dhis2_uid',
            field=models.CharField(blank=True, db_index=True, help_text='DHIS2 TrackedEntityInstance UID assigned after successful push.', max_length=100, null=True),
        ),
    ]
