# Generated by Django 5.1 on 2026-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='min_interval_days',
            field=models.PositiveIntegerField(default=0, help_text='Minimum days between this dose and the previous dose of the same vaccine.'),
        ),
    ]
