# Generated by Django 5.1.15 on 2026-05-06 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0002_camp_code_camp_estimated_population_and_more'),
        ('children', '0005_add_visit_request'),
        ('vaccinations', '0002_vaccine_min_interval_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_sessions', to='camps.camp')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_clinic_sessions', to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_sessions', to='vaccinations.vaccine')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicSessionAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DONE', 'Done'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped (contraindicated)')], default='DONE', max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_attendances', to='children.child')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='vaccinations.clinicsession')),
                ('vaccination_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_attendance', to='vaccinations.vaccinationrecord')),
            ],
            options={
                'unique_together': {('session', 'child')},
            },
        ),
    ]
