# Generated by Django 5.1.15 on 2026-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0003_add_clinic_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='dhis2_event_uid',
            field=models.CharField(blank=True, db_index=True, help_text='DHIS2 tracker Event UID assigned after successful push.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='source',
            field=models.CharField(default='LOCAL', help_text='LOCAL (recorded in Ikibondo) or DHIS2 (pulled from registry).', max_length=20),
        ),
    ]
