# Generated by Django 5.2.16 on 2026-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0004_add_vaccination_dhis2_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='scheduled_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DONE', 'Done'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped (contraindicated)')], db_index=True, default='SCHEDULED', max_length=20),
        ),
    ]
