# Generated by Django 5.1.15 on 2026-04-29 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def assign_unique_camp_codes(apps, schema_editor):
    """Assign a unique code to any camp that has an empty-string code."""
    Camp = apps.get_model('camps', 'Camp')
    for camp in Camp.objects.filter(code=''):
        camp.code = str(camp.id)[:8]
        camp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add code as nullable, no unique yet
        migrations.AddField(
            model_name='camp',
            name='code',
            field=models.CharField(default='', max_length=20, null=True, blank=True),
        ),
        # Step 2: Assign unique codes to existing rows
        migrations.RunPython(assign_unique_camp_codes, migrations.RunPython.noop),
        # Step 3: Make non-nullable and add unique constraint
        migrations.AlterField(
            model_name='camp',
            name='code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='estimated_population',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camp',
            name='managing_body',
            field=models.CharField(blank=True, default='MINEMA/UNHCR', max_length=100),
        ),
        migrations.AddField(
            model_name='camp',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('transitioning', 'Transitioning')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='CampZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('estimated_households', models.PositiveIntegerField(default=0)),
                ('estimated_population', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='camps.camp')),
            ],
            options={
                'verbose_name': 'Camp Zone',
                'ordering': ['camp', 'name'],
                'unique_together': {('camp', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CHWZoneAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chw_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('chw_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chw_zone_assignments', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chws', to='camps.campzone')),
            ],
            options={
                'verbose_name': 'CHW Zone Assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneCoordinatorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_assignments', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='camps.campzone')),
            ],
            options={
                'verbose_name': 'Zone Coordinator Assignment',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'zone')},
            },
        ),
    ]
