# Generated by Django 5.2.13 on 2026-04-28 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPredictionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_name', models.CharField(choices=[('malnutrition', 'Malnutrition Classifier'), ('growth', 'Growth Trajectory Predictor'), ('vaccination', 'Vaccination Dropout Predictor')], max_length=50)),
                ('model_version', models.CharField(default='v1', max_length=20)),
                ('input_data', models.JSONField(help_text='Feature values passed to the model')),
                ('output_data', models.JSONField(help_text='Full prediction output including probabilities')),
                ('predicted_label', models.CharField(max_length=50)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='children.child')),
            ],
            options={
                'verbose_name': 'ML Prediction Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
